FROM archlinux:latest

RUN pacman -Syu --noconfirm \
    base-devel \
    git \
    sudo \
    systemd \
    namcap \
    && pacman -Scc --noconfirm

RUN useradd -m builder \
    && echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder \
    && chmod 0440 /etc/sudoers.d/builder

# Install paru (AUR helper)
USER builder
WORKDIR /tmp
RUN git clone https://aur.archlinux.org/paru.git \
    && cd paru \
    && makepkg -si --noconfirm \
    && cd .. && rm -rf paru

RUN paru -S --noconfirm ocproxy-bin

WORKDIR /build
